version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Basis.API/Dockerfile
    container_name: basis_api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqlserver;Database=BasisDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
    expose:
      - 8001
      - 8080
    ports:
      - "8081:8081"
      - "5000:8080"
    working_dir: /app

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
    driver: local